export const EXPERIENCES = [
  {
    id: 1,
    role: 'Desenvolvedor Full-Stack',
    company: 'Polícia Militar do Pará (PMPA)',
    location: 'Belém, PA',
    period: 'Jun 2025 – Presente',
    type: 'CLT / Institucional',
    description:
      'Desenvolvimento de sistemas críticos em ambiente governamental.',
    highlights: [
      'Eliminei 100% do trabalho manual de conferência de documentos — processamento reduzido de 3–4 semanas para 5–10 minutos',
      'Arquitetei Sistema de Gestão Acadêmica full-stack com DDD e Clean Architecture',
      'Stack: TypeScript, Fastify, React/Vite.js, Prisma ORM, PostgreSQL, Redis',
      'APIs RESTful com autenticação JWT, RBAC e documentação Swagger completa',
      'Infraestrutura containerizada com Docker e pipelines CI/CD automatizados',
      'Sistema de auditoria e rastreabilidade completa conforme requisitos governamentais',
      'Pipeline de automação de documentos em Python integrado ao Google Colab e Drive',
    ],
    stack: [
      'TypeScript',
      'Fastify',
      'React',
      'Vite',
      'PostgreSQL',
      'Redis',
      'Docker',
      'Python',
      'CI/CD',
    ],
  },
  {
    id: 2,
    role: 'Desenvolvedor Frontend',
    company: 'Zenith Inova',
    location: 'Belém, PA',
    period: 'Mai 2024 – Mai 2025',
    type: '1 ano 1 mês',
    description: 'Desenvolvimento de aplicações web modernas e responsivas.',
    highlights: [
      'Aplicações web com React.js, Next.js e TypeScript focadas em performance e UX',
      'Componentes reutilizáveis seguindo Clean Code e princípios SOLID',
      'Integração de frontends com APIs RESTful com gestão de estado complexo',
      'Testes automatizados com Jest e Testing Library',
      'Otimização de performance: lazy loading, code splitting, memoization',
      'Participação ativa em discovery, refinamento de requisitos e estimativas técnicas',
    ],
    stack: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Jest', 'Git'],
  },
];
