export const PROJECTS = [
  {
    id: 1,
    title: 'Sistema de Gestão Acadêmica — PMPA',
    subtitle: 'Full-Stack',
    description: [
      'Sistema full-stack para gestão acadêmica da Polícia Militar do Pará. Eliminou 100% do trabalho manual de conferência de documentos, reduzindo processamento de semanas para minutos.',
      'Inclui gestão de professores, alocações, carga horária, geração de documentos oficiais e auditoria completa.',
    ],
    image: null,
    stack: [
      'TypeScript',
      'Fastify',
      'React',
      'Vite.js',
      'PostgreSQL',
      'Redis',
      'Docker',
      'Prisma',
      'JWT',
    ],
    category: 'Full-Stack',
    highlights: [
      'Arquitetura DDD + Clean Architecture',
      'RBAC e autenticação JWT',
      'CI/CD automatizado',
      'Auditoria governamental completa',
    ],
    github: null,
    live: null,
    status: 'Em produção',
  },
  {
    id: 2,
    title: 'Pipeline de Automação de Documentos',
    subtitle: 'Automação',
    description: [
      'Script Python automatizado integrado ao Google Colab e Google Drive para geração de documentos oficiais a partir de templates e planilhas.',
      'Reduziu tempo de processamento de dias para minutos.',
    ],
    image: null,
    stack: ['Python', 'Google Cloud API', 'Google Colab', 'Google Drive API'],
    category: 'Automação',
    highlights: [
      'Geração automática de documentos oficiais',
      'Integração com Google Workspace',
      'Processamento em lote',
    ],
    github: null,
    live: null,
    status: 'Em produção',
  },
  {
    id: 3,
    title: 'Portfólio Pessoal',
    subtitle: 'Frontend',
    description: [
      'Portfólio moderno e responsivo com Next.js, TypeScript e Tailwind CSS.',
      'SSR, otimização de performance, SEO e deploy automatizado na Vercel.',
    ],
    image: null,
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    category: 'Frontend',
    highlights: [
      'Server-Side Rendering (SSR)',
      'Deploy automatizado via CI/CD',
      'SEO otimizado',
    ],
    github: 'https://github.com/AdlerCastro',
    live: 'https://portfolio-adler.vercel.app',
    status: 'Live',
  },
];
