export const PROJECTS = [
  {
    id: 1,
    title: 'Boletim Acadêmico — PMPA',
    subtitle: 'Sistema Oficial de Gestão do Desempenho Acadêmico',
    description: [
      'Sistema oficial de registro, acompanhamento e controle do desempenho acadêmico dos discentes vinculados ao Sistema de Educação Policial Militar da PMPA.',
      'Instituído pela Portaria nº 144/2025 – GAB CMDO/PMPA como instrumento oficial da corporação. Em produção, integrando processos pedagógicos e administrativos com consulta em tempo real, geração automatizada de relatórios e auditoria completa.',
    ],
    image: null,
    stack: [
      'TypeScript',
      'Fastify',
      'Node.js',
      'PostgreSQL',
      'Redis',
      'Prisma ORM',
      'Docker',
      'DDD',
      'Clean Architecture',
      'JWT',
      '2FA',
      'Zod',
      'Vitest',
    ],
    category: 'Full-Stack',
    status: 'Em produção',
    visibility: 'private',
    role: 'Desenvolvedor Full-Stack',
    team: 'Equipe SSTE - PMPA',
    award: {
      type: 'Elogio Oficial',
      issuer: 'Departamento-Geral de Educação e Cultura — PMPA',
      authority: 'Cel QOPM Ubirajara Magela de Sousa Falcão',
      document: 'Portaria nº 144/2025 – GAB CMDO/PMPA',
      citation:
        'Reconhecimento pelo elevado grau de comprometimento, competência técnica e espírito de corpo, cuja dedicação resultou em significativa modernização, padronização e ampliação da transparência institucional no acesso e na gestão das informações acadêmicas.',
    },
    highlights: [
      'Sistema em produção — instituído por Portaria oficial nº 144/2025',
      'Publicação e consulta de notas em tempo real para todos os discentes',
      'Análise de rendimento individual por aluno, polo e curso',
      'Geração automatizada de relatórios acadêmicos',
      'Integração entre processos pedagógicos e administrativos',
      'Auditoria completa de todas as operações acadêmicas',
      'Cobertura de cursos de formação inicial, continuada e complementar',
      'Modernização e padronização da gestão educacional da corporação',
      'Reconhecimento oficial por elogio consignado pelo Chefe do DGEdC',
    ],
    metrics: [
      { label: 'Status', value: 'Produção' },
      { label: 'Portaria', value: 'nº 144/2025' },
      { label: 'Reconhecimento', value: 'Elogio Oficial' },
      { label: 'Cobertura', value: '100%' },
    ],
    github: null,
    live: null,
  },
  {
    id: 2,
    title: 'Teacher Management System — PMPA',
    subtitle: 'Plataforma de Gestão de Docentes EAD',
    description: [
      'Plataforma desenvolvida para a Polícia Militar do Pará com o objetivo de automatizar e digitalizar o processo de seleção, credenciamento e acompanhamento de docentes em instituições de ensino à distância (EAD).',
      'Sistema em desenvolvimento ativo, projetado para digitalizar 90% das etapas de credenciamento e reduzir em 60% o tempo de triagem de docentes.',
    ],
    image: null,
    stack: [
      'TypeScript',
      'Fastify',
      'Node.js',
      'PostgreSQL',
      'Redis',
      'BullMQ',
      'Prisma ORM',
      'Docker',
      'DDD',
      'Clean Architecture',
      'JWT',
      '2FA',
      'Zod',
      'Vitest',
    ],
    category: 'Full-Stack',
    status: 'Em desenvolvimento',
    visibility: 'private',
    role: 'Tech Lead & Desenvolvedor Full-Stack',
    team: 'Equipe SSTE - PMPA',
    domains: [
      {
        icon: '📚',
        title: 'Gestão Acadêmica',
        items: ['Cursos', 'Disciplinas', 'Polos', 'Carga Horária'],
      },
      {
        icon: '👥',
        title: 'Gestão de Pessoas',
        items: [
          'Usuários (RBAC)',
          'Docentes',
          'Supervisores',
          'Credenciamento',
        ],
      },
      {
        icon: '💰',
        title: 'Gestão Financeira',
        items: ['Remuneração por titulação', 'Multiplicadores', 'Relatórios'],
      },
      {
        icon: '🔐',
        title: 'Segurança & Auditoria',
        items: [
          'JWT + 2FA obrigatório',
          'Audit Logs completos',
          'Rate Limiting',
        ],
      },
    ],
    highlights: [
      'Arquitetura DDD + Clean Architecture (4 camadas)',
      'RBAC com 4 níveis: Developer, Admin, Supervisor, Teacher',
      'Autenticação JWT + 2FA obrigatório para todos os usuários',
      'Cálculo automático de remuneração por titulação do docente',
      'Geração automática de atas em PDF',
      'Auditoria completa: 100% das ações críticas rastreadas',
      'Processamento assíncrono com BullMQ',
      '23+ migrações de banco em 3 sprints concluídas',
      'Substituição de docentes com ata automática e cálculo de horas restantes',
    ],
    metrics: [
      { label: 'Digitalização projetada', value: '90%' },
      { label: 'Redução no credenciamento', value: '60%' },
      { label: 'Cobertura de auditoria', value: '100%' },
      { label: 'Migrações entregues', value: '23+' },
      { label: 'Sprints concluídas', value: '3' },
      { label: 'Módulos de aplicação', value: '9' },
    ],
    github: null,
    live: null,
  },
  {
    id: 3,
    title: 'Pipeline de Automação de Documentos',
    subtitle: 'Automação',
    description: [
      'Script Python automatizado integrado ao Google Colab e Google Drive para geração de documentos oficiais a partir de templates e planilhas.',
      'Reduziu tempo de processamento de dias para minutos.',
    ],
    image: null,
    stack: ['Python', 'Google Cloud API', 'Google Colab', 'Google Drive API'],
    category: 'Automação',
    highlights: [
      'Geração automática de documentos oficiais',
      'Integração com Google Workspace',
      'Processamento em lote',
    ],
    github: null,
    live: null,
    status: 'Em produção',
  },
  {
    id: 4,
    title: 'Portfólio Pessoal',
    subtitle: 'Frontend',
    description: [
      'Portfólio moderno e responsivo com Next.js, TypeScript e Tailwind CSS.',
      'SSR, otimização de performance, SEO e deploy automatizado na Vercel.',
    ],
    image: null,
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    category: 'Frontend',
    highlights: [
      'Server-Side Rendering (SSR)',
      'Deploy automatizado via CI/CD',
      'SEO otimizado',
    ],
    github: 'https://github.com/AdlerCastro',
    live: 'https://portfolio-adler.vercel.app',
    status: 'Live',
  },
];
